name: flutter_web_and_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  injectable: ^2.3.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  network_info_plus: ^4.0.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  route_map: ^0.0.16
  syncfusion_flutter_calendar: ^22.2.12
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  route_map_generator: ^0.0.16
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  responsive_builder: ^0.7.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
